#! /bin/sh

# Autostart
xsetroot -cursor_name left_ptr
#pulseeffects --gapplication-service &
sxhkd -c ~/.config/sxhkd/sxhkd_bspwm &
# Monitor Configuration
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        3
bspc config window_gap          0
bspc config top_padding         0
bspc config right_padding       0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled follow=on
bspc rule -a Alacritty state=floating follow=on
bspc rule -a Zathura state=tiled follow=on
bspc rule -a Screenkey manage=off
